---
- name: Update nginx if needed
  hosts: vps
  become: true
  become_user: root
  tasks:

    - name: Ensure nginx is at the latest version
      ansible.builtin.package:
        name: nginx
        state: latest
      notify: restart nginx

    - name: Ensure nginx is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
...
